Repository developersociety/commonslibrary, pull requests merged in 2019-11, with the labels that each got.

#140 replace old explore (tags overview) view with categories list view
  apps/core/tests/test_views.py
  apps/core/views.py
  apps/resources/tests/test_views.py
  apps/resources/urls.py
  commonslibrary/urls.py
  templates/explore/explore_list.html
  templates/includes/header.html
  templates/resources/resourcecategory_detail.html
Labels: backend

#138 change to sprite title
  templates/includes/icon_sprite.html
Labels: frontend

#139 Category final feedback
  static/src/js/resource/resource.jsx
  static/src/scss/resources/_categories.scss
  static/src/scss/resources/_resources.scss
  templates/includes/resource.html
Labels: frontend

#141 Bulk categorise resources + admin display & filtering
  apps/resources/admin.py
  apps/resources/models.py
  apps/resources/urls.py
  apps/resources/views.py
  templates/resources/admin/categorise_resources.html
Labels: backend, enhancement

#142 show search results ordered by latest first.
  static/src/js/index.jsx
  static/src/js/resource/resource_filter.jsx
Labels: frontend
